# Site settings
title: Jeffrey Jurgajtis
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a developer who enjoys solving business problems with software and
  learning about new web technologies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeffreyjurgajtis.github.io" # the base hostname & protocol for your site
twitter_username: jeffjurgajtis
github_username:  jeffreyjurgajtis

# Build settings
markdown: kramdown
